version: '3'
services:
# React
  client:
    build: .
    image: frontend-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Ho_Chi_Minh
    container_name: swd391-client
    restart: always
    command: npm start
    networks:
      - swd391-network

  # Nginx
  nginx:
    build: ./nginx.conf
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: swd391-nginx
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx.conf/data:/data
      - ./nginx.conf/letsencrypt:/etc/letsencrypt
    depends_on:
      - client
    networks:
      - swd391-network
networks:
  swd391-network:
    driver: bridge
